package com.example.compositioncamera;
import android.Manifest; import android.app.*; import android.os.*; import android.content.pm.PackageManager; import android.graphics.*; import android.hardware.camera2.*; import android.media.*; import android.view.*; import android.widget.*; import java.nio.*; import java.util.*;
public class MainActivity extends Activity {
 FrameLayout root; TextureView preview; CompositionOverlayView overlay; CameraDevice camera; CameraCaptureSession session; ImageReader reader;
 int template=0; long last=0; float tx=.5f,ty=.5f; final String[] names={"Золоте січення","Правило третин","Золотий трикутник","Діагоналі","Центральна симетрія"};
 public void onCreate(Bundle b){super.onCreate(b); root=new FrameLayout(this); preview=new TextureView(this); overlay=new CompositionOverlayView(this); root.addView(preview);root.addView(overlay);setContentView(root);
  if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.CAMERA},7);
  preview.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){open();} public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){} public boolean onSurfaceTextureDestroyed(SurfaceTexture s){return true;} public void onSurfaceTextureUpdated(SurfaceTexture s){}});
 }
 void open(){try{CameraManager cm=(CameraManager)getSystemService(CAMERA_SERVICE);String id=cm.getCameraIdList()[0];reader=ImageReader.newInstance(320,240,ImageFormat.YUV_420_888,2);reader.setOnImageAvailableListener(r->{Image im=r.acquireLatestImage();if(im!=null){analyze(im);im.close();}},null);if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)cm.openCamera(id,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;start();}public void onDisconnected(CameraDevice c){c.close();}public void onError(CameraDevice c,int e){c.close();}},null);}catch(Exception e){}}
 void start(){try{Surface ps=new Surface(preview.getSurfaceTexture());camera.createCaptureSession(Arrays.asList(ps,reader.getSurface()),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession s){session=s;try{CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);b.addTarget(ps);b.addTarget(reader.getSurface());b.set(CaptureRequest.CONTROL_AF_MODE,CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);s.setRepeatingRequest(b.build(),null,null);}catch(Exception e){}}public void onConfigureFailed(CameraCaptureSession s){}},null);}catch(Exception e){}}
 void analyze(Image im){ByteBuffer y=im.getPlanes()[0].getBuffer();byte[] a=new byte[y.remaining()];y.get(a);int w=im.getWidth(),h=im.getHeight(),rs=im.getPlanes()[0].getRowStride();double sx=0,sy=0,sum=0;for(int yy=4;yy<h-4;yy+=5)for(int xx=4;xx<w-4;xx+=5){int i=yy*rs+xx;if(i+rs>=a.length)continue;int v=a[i]&255;int gx=Math.abs(v-(a[i+4]&255));int gy=Math.abs(v-(a[i+rs*4]&255));double q=gx+gy+2;sx+=q*xx;sy+=q*yy;sum+=q;}if(sum>0){tx=(float)Math.max(.12,Math.min(.88,sx/sum/w));ty=(float)Math.max(.12,Math.min(.88,sy/sum/h));}long now=System.currentTimeMillis();if(now-last>700){template=(template+1)%names.length;last=now;}final int t=template;final float x=tx,yy=ty;runOnUiThread(()->overlay.setData(t,names[t],x,yy));}
 @Override protected void onDestroy(){super.onDestroy();try{if(session!=null)session.close();if(camera!=null)camera.close();}catch(Exception e){}}
}